POST http://localhost:8888/shuffle
Content-Type: application/json

{
  "user": "popug",
  "password": "popug"
}

###
POST http://localhost:8888/login
Content-Type: application/json

{
  "user": "popug",
  "password": "popug"
}
